version: "3"

services:

  postgres:
    image: 'postgres'
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

    
